#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.34014
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("L12_QRCode.Resource", IsApplication=true)]

namespace L12_QRCode
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::MWBarcodeScanner.Resource.Drawable.flashbuttonoff = global::L12_QRCode.Resource.Drawable.flashbuttonoff;
			global::MWBarcodeScanner.Resource.Drawable.flashbuttonon = global::L12_QRCode.Resource.Drawable.flashbuttonon;
			global::MWBarcodeScanner.Resource.Drawable.overlay = global::L12_QRCode.Resource.Drawable.overlay;
			global::MWBarcodeScanner.Resource.Id.RelativeLayout1 = global::L12_QRCode.Resource.Id.RelativeLayout1;
			global::MWBarcodeScanner.Resource.Id.flashButton = global::L12_QRCode.Resource.Id.flashButton;
			global::MWBarcodeScanner.Resource.Id.overlayImage = global::L12_QRCode.Resource.Id.overlayImage;
			global::MWBarcodeScanner.Resource.Id.preview_view = global::L12_QRCode.Resource.Id.preview_view;
			global::MWBarcodeScanner.Resource.Layout.scanner = global::L12_QRCode.Resource.Layout.scanner;
			global::MWBarcodeScanner.Resource.String.library_name = global::L12_QRCode.Resource.String.library_name;
			global::ZXing.Mobile.Resource.Id.contentFrame = global::L12_QRCode.Resource.Id.contentFrame;
			global::ZXing.Mobile.Resource.Layout.zxingscanneractivitylayout = global::L12_QRCode.Resource.Layout.zxingscanneractivitylayout;
			global::ZXing.Mobile.Resource.Layout.zxingscannerfragmentlayout = global::L12_QRCode.Resource.Layout.zxingscannerfragmentlayout;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int flashbuttonoff = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int flashbuttonon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Icon = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int overlay = 2130837507;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060002
			public const int RelativeLayout1 = 2131099650;
			
			// aapt resource value: 0x7f060000
			public const int btnScanditSDK = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int btnZXing = 2131099649;
			
			// aapt resource value: 0x7f060006
			public const int contentFrame = 2131099654;
			
			// aapt resource value: 0x7f060005
			public const int flashButton = 2131099653;
			
			// aapt resource value: 0x7f060004
			public const int overlayImage = 2131099652;
			
			// aapt resource value: 0x7f060003
			public const int preview_view = 2131099651;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int scanner = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int zxingscanneractivitylayout = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int zxingscannerfragmentlayout = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7f040000
			public const int beep = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int camera_swap_icon = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int camera_swap_icon_pressed = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int flashlight_turn_off_icon = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int flashlight_turn_off_icon_pressed = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int flashlight_turn_on_icon = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int flashlight_turn_on_icon_pressed = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int ic_btn_search = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int poweredby2x = 2130968584;
			
			static Raw()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Raw()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050002
			public const int ApplicationName = 2131034114;
			
			// aapt resource value: 0x7f050001
			public const int Hello = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int library_name = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
