#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.34014
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("MWBCameraDemo.Resource", IsApplication=true)]

namespace MWBCameraDemo
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::MWBarcodeScanner.Resource.Drawable.flashbuttonoff = global::MWBCameraDemo.Resource.Drawable.flashbuttonoff;
			global::MWBarcodeScanner.Resource.Drawable.flashbuttonon = global::MWBCameraDemo.Resource.Drawable.flashbuttonon;
			global::MWBarcodeScanner.Resource.Drawable.overlay = global::MWBCameraDemo.Resource.Drawable.overlay;
			global::MWBarcodeScanner.Resource.Id.RelativeLayout1 = global::MWBCameraDemo.Resource.Id.RelativeLayout1;
			global::MWBarcodeScanner.Resource.Id.flashButton = global::MWBCameraDemo.Resource.Id.flashButton;
			global::MWBarcodeScanner.Resource.Id.overlayImage = global::MWBCameraDemo.Resource.Id.overlayImage;
			global::MWBarcodeScanner.Resource.Id.preview_view = global::MWBCameraDemo.Resource.Id.preview_view;
			global::MWBarcodeScanner.Resource.Layout.scanner = global::MWBCameraDemo.Resource.Layout.scanner;
			global::MWBarcodeScanner.Resource.String.library_name = global::MWBCameraDemo.Resource.String.library_name;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int flashbuttonoff = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int flashbuttonon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Icon = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int overlay = 2130837507;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050001
			public const int RelativeLayout1 = 2131034113;
			
			// aapt resource value: 0x7f050004
			public const int flashButton = 2131034116;
			
			// aapt resource value: 0x7f050000
			public const int myButton = 2131034112;
			
			// aapt resource value: 0x7f050003
			public const int overlayImage = 2131034115;
			
			// aapt resource value: 0x7f050002
			public const int preview_view = 2131034114;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int scanner = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int app_name = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int library_name = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
